student_count = 24
#first, we print the list of students
puts "The students of my cohort at Makers Academy"
puts "-------------------"
puts "Javier Silverio"
puts "Elliot Lewis"
puts "Ben Tillett"
puts "Vincent Koch"
puts "Michelle Ballard"
puts "Nick Roberts"
puts "Tatiana Soukiassian"
puts "Mervé Silk"
puts "Albert Vallverdu"
puts "Lovis Schultze"
puts "Henry Stanley"
puts "Spike Lindsey"
puts "Ruth Earle"
puts "Andy Gates"
puts "Faisal Aydarus"
puts "Ethel Ng"
puts "Kevin Daniells"
puts "Maya Driver"
puts "Leopold Kwok"
puts "James McNeil"
puts "Jerome Pratt"
puts "David Wickes"
puts "Chris Oatley"
puts "Marc Singh"
#finally, we print the total
puts "Overall, we have #{student_count} great students"
